language: node_js
node_js:
- '11'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: 
    - git.coding.net
    - 118.25.166.124
    - github.com
    - 192.30.255.112
before_install:
- openssl aes-256-cbc -K $encrypted_3e10d11e4aff_key -iv $encrypted_3e10d11e4aff_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'whyliam'
- npm install hexo-cli -g
install:
- npm install
- npm install hexo --save
- npm audit fix
script:
- git submodule update --recursive --remote
- git clone https://github.com/theme-next/theme-next-algolia-instant-search themes/next/source/lib/algolia-instant-search
- git clone https://github.com/theme-next/theme-next-fancybox3 themes/next/source/lib/fancybox
- hexo clean --config source/_data/next.yml
- hexo generate --config source/_data/next.yml
- hexo algolia --config source/_data/next.yml
- hexo recommend --config source/_data/next.yml
after_success:
- hexo deploy --config source/_data/next.yml
